# Generated by Django 5.1.7 on 2025-05-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ingredients', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
            ],
        ),
    ]
