# Generated by Django 5.1.7 on 2025-05-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='image',
            new_name='pic',
        ),
    ]
