# Generated by Django 5.1.7 on 2025-05-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_rename_image_recipes_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
