# Generated by Django 5.1.7 on 2025-05-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_alter_recipes_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='pic',
            field=models.FileField(upload_to='recipe_images/'),
        ),
    ]
